server:
  port: 8082
  servlet:
    context-path: /dev


spring:
  datasource:
    driver-class-name: your driver
    url: your url
    username: postgres
    password: your password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: your host
      port: 14597
      password: your password
      username: default

cloudinary:
  cloud-name: your cloud_name
  api-key: your api_key
  api-secret: your api_secret_key
