server:
  port: 8082
  servlet:
    context-path: /dev

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/hotel_booking_dev"
    username: postgres
    password: 0911600379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis-14597.c291.ap-southeast-2-1.ec2.cloud.redislabs.com
      port: 14597
      password: YnttLGa38uDs29MUZ132smcVDv4Icfzn
      username: default